[theme]
base = "dark"
primaryColor = "#02c39a"
backgroundColor = "#07101c"
secondaryBackgroundColor = "#0b1626"
textColor = "#d9e1ec"
font = "sans serif"

[server]
headless = true

# redeploy-trigger: 2026-03-08
